// Generated by https://quicktype.io

export interface category {
    id:         number;
    is_default: boolean;
    title:      string;
    avatar:     null | string;
    position:   number;
    is_enable:  boolean;
    is_visible: boolean;
    parent:     number | null;
    childs:     category[];
}
